### PR TITLE
hw: bom: Adjust format to one-line-per-PN

### PR DESCRIPTION
**Pull request by mlyle**
So that multiple refdeses can be on one line.  Easier to place from,
plays nicer with OctoPart.

### CODE REVIEW

**Comment by mlyle** [comment]
@droidicus -- cool with you?

**Comment by tracernz** [comment]
Much better idea.

**Comment by droidicus** [comment]
@mlyle, did you do this manually or with the KiCAD tool? I would prefer if the project was updated to do this instead of doing it manually or hiding the script invocation.

**Comment by mlyle** [comment]
I did it with this chunk of XSL: https://forum.kicad.info/t/bom-grouped-by-reference/261

Not sure it makes sense to check that into the OL tree though.

**Comment by droidicus** [comment]
The script I used is part of the standard KiCad install, it probably makes sense to at least document how this BOM was generated. If that is done then LGTM.

**Comment by mlyle** [comment]
Well, it's effectively done here ;)

**Pull request merged**
